export const ENV_NODE_ENV = 'NODE_ENV';
export const ENV_SSH_TUNNEL_FORWARDED_PORT = 'SSH_TUNNEL_FORWARDED_PORT';
export const ENV_SSH_TUNNEL_SERVER_HOST = 'SSH_TUNNEL_SERVER_HOST';
export const ENV_SSH_TUNNEL_SERVER_PORT = 'SSH_TUNNEL_SERVER_PORT';
export const ENV_SSH_TUNNEL_SERVER_USERNAME = 'SSH_TUNNEL_SERVER_USERNAME';
export const ENV_SSH_TUNNEL_SERVER_PASSWORD = 'SSH_TUNNEL_SERVER_PASSWORD';

export const ENV_DB_HOST = 'DB_HOST';
export const ENV_DB_USERNAME = 'DB_USERNAME';
export const ENV_DB_PASSWORD = 'DB_PASSWORD';
export const ENV_DB_DATABASE = 'DB_DATABASE';

export const ENV_JWT_ISSUER = 'JWT_ISSUER';
export const ENV_JWT_SECRET = 'JWT_SECRET';
export const ENV_HASH_ROUND_KEY = 'HASH_ROUND_KEY';
